apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: {{ .Release.Name }}-app
        image: {{ .Values.container.image }}
        ports:
        - name: {{ .Release.Name }}-app-port
          containerPort: 8080
        env:
          - name: DB_HOST
            value: postgres-service
          - name: DB_USER
            value: myuser
          - name: DB_PASSWORD
            value: mypassword
        resources:
          requests:
            memory: {{ .Values.requests.memory }}
            cpu: {{ .Values.requests.cpu }}
          limits:
            memory: {{ .Values.limits.memory }}
            cpu: {{ .Values.limits.cpu }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
