apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- ../../base

namePrefix: prod-

commonLabels:
  app: backend

namespace: lab8

images:
- name: aba111f/app
  newTag: v6

patches:
- path: replicas-patch.yaml

- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: backend-ingress
    spec:
      rules:
      - host: backend-prod.com
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:              
                name: backend-service
                port:
                  number: 80
