apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- ../../base

commonLabels:
  app: backend

namespace: lab8
namePrefix: dev-

images: 
- name: aba111f/app
  newTag: v6

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backend
    spec: 
      replicas: 2
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: backend-ingress
    spec:
      rules:
      - host: backend-dev.com
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:              
                name: backend-service
                port:
                  number: 80
